use_default_settings: true

general:
  instance_name: "ChainLens Search"
  debug: false

search:
  safe_search: 1
  autocomplete: ""
  formats:
    - html
    - json

server:
  secret_key: "change-this-with-the-SEARXNG_SECRET-environment-variable"
  limiter: false
  image_proxy: false

ui:
  static_use_hash: true
